### ISSUE TITLE
ImportError: cannot import name 'deprecated_endpoints'

### ISSUE THREAD

**Issue by EEECGWood** [NVIDIA-Jetson/tf_trt_models#46]
import tensorflow.contrib.tensorrt as trt

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/tensorrt/__init__.py", line 25, in <module>
    from tensorflow.contrib.tensorrt.python import *
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/tensorrt/python/__init__.py", line 22, in <module>
    from tensorflow.contrib.tensorrt.python.ops import trt_engine_op
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/tensorrt/python/ops/trt_engine_op.py", line 25, in <module>
    from tensorflow.contrib.tensorrt.ops.gen_trt_engine_op import *
  File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/tensorrt/ops/gen_trt_engine_op.py", line 24, in <module>
    from tensorflow.python.util.deprecation import deprecated_endpoints
ImportError: cannot import name 'deprecated_endpoints'

can u guys giive me a favor?

**Comment by AKhileshPothuri** [comment]
Hey..I'm facing the same issue. Can you tell me how have you solved it earlier?
