### ISSUE TITLE
Import error: cannot import 'pipeline_pb2'

### ISSUE THREAD

**Issue by RogerAylagas** [NVIDIA-Jetson/tf_trt_models#48]
Hi,
I am running on Jetson TX2.
I have followed the setup instructions and after finishing I have copied your jupyter notebook example code to a python script.
While trying to exectue it the following error occurs:

> Traceback (most recent call last):
>   File "run.py", line 14, in <module>
>     from tf_trt_models.detection import download_detection_model, build_detection_graph
>   File "/home/nvidia/.local/lib/python3.5/site-packages/tf_trt_models-0.0-py3.5.egg/tf_trt_models/detection.py", line 1, in <module>
> ImportError: cannot import name 'pipeline_pb2'

Can anyone help me with this?
Thank you

**Comment by RogerAylagas** [comment]
I noticed that the folder /home/nvidia/.local/lib/python3.5/site-packages/tf_trt_models-0.0-py3.5.egg is not there. Why?

**Comment by kongkongthu** [comment]
I met the same question like yours, have you solved it? If so, can you show how you solved it.

**Comment by jkjung-avt** [comment]
Did you run 'install.sh'?  I think the problem is caused by not compiling the '.proto' files with 'protoc'.  More specifically, that should be done by this line of command in 'install.sh':

https://github.com/NVIDIA-AI-IOT/tf_trt_models/blob/master/install.sh#L26

**Comment by kongkongthu** [comment]
thank you very much, I forgot the install step.
