### ISSUE TITLE
Import error: cannot import 'pipeline_pb2'

### ISSUE THREAD

**Issue by RogerAylagas** [NVIDIA-Jetson/tf_trt_models#49]
Hi,
I have followed the setup instructions and after finishing I have copied your jupyter notebook example code to a python script.
While trying to exectue it the following error occurs:

Traceback (most recent call last):
  File "run.py", line 14, in <module>
    from tf_trt_models.detection import download_detection_model, build_detection_graph
  File "/home/nvidia/.local/lib/python3.5/site-packages/tf_trt_models-0.0-py3.5.egg/tf_trt_models/detection.py", line 1, in <module>
ImportError: cannot import name 'pipeline_pb2'

Can anyone help me with this?
Thank you

**Comment by hgao9** [comment]
Hi there, I actually came from your other post: How to read .pcd.bin? #2647

I am having some trouble loading pcd.bin file, just wondering have you solved this issue? If so, do you mind sharing your solution? My email is listed in the profile, or you can just type it here. Thank you!
