### ISSUE TITLE
Import Error: cannot import name 'exporter'

### ISSUE THREAD

**Issue by tfoxkustudent** [NVIDIA-Jetson/tf_trt_models#52]
Traceback (most recent call last):
  File "jetson_stream.py", line 9, in <module>
    from object_detector_trt import ObjectDetectorTRT
  File "/home/nano/sc2.2/scripts/mobile_detector/object_detector_trt.py", line 5, in <module>
    from tf_trt_models.detection import download_detection_model, \
  File "/home/nano/.local/lib/python3.6/site-packages/tf_trt_models-0.0-py3.6.egg/tf_trt_models/detection.py", line 3, in <module>
ImportError: cannot import name 'exporter'

**Comment by jaybdub** [comment]
Hi tfoxkustudent,

Have you run the ``install.sh`` script in this repository?  It seems like the TensorFlow object detection API hasn't been installed.  This script should handle that.

Best,
John
